name: gutenberg-book-collector-api
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/Collector
    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        mongodb-version: [ '7.0.12' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: supercharge/mongodb-github-action@1.11.0
      - run: npm install
      - run: npm test